### PR TITLE
Adding TL63, TL255 and ORCA2 support

### PR DESCRIPTION
**Pull request by oloapinivad**
As per title, we extend the support to TL63 and TL255 grids (only the former has been tested) and to ORCA2 grid (which has been tested in coupled mode with TL63 only). 

The latter has been particularly easy and I am wondering if we did everything in the right way... If this is the case, the `rdy2cpl` code is very smooth, great job :-)

Please let me know if you need further testing or anything else.

### CODE REVIEW

**Comment by uwefladrich** [comment]
Hi @oloapinivad,

The changes look good to me and yes, the ORCA2 integration is supposed to be so easy :grin: 

The only thing I would complain (only a little bit) about is the shape of the branch. It is (arguably) better to rebase dev branches onto `main` for PRs because that makes it a bit easier to see what actually happened. In this case, you would get rid of the changes history related to the tco399 integration. It would not change anything in the actual code, though.

I have made a rebase onto `main` (after tco399) locally and would like to push it to your repo. However, as this brings a modified history (but with all your commits intact), I ask for your permission before I do so.

In this rebase, I took the freedom to modify the commits slightly

- removed an extra space in `rdy2cpl/grids/base/tl/__init__.py`
- skip the changes to `.gitignore`

The latter change is a good idea, actually, but I would prefer to have it separately from this PR.

So, if it is okay with you, I would push and then we can go on and merge.

**Comment by uwefladrich** [comment]
Regarding further testing: I think we are okay with the tests you have been doing. It is in general not so easy (or even meaningful) to try and test every grid combination here. This has to be done with/in the model.

**Comment by oloapinivad** [comment]
Thanks @uwefladrich, please proceed. I added you to my fork so that you can push. 

Yes I am aware I did some kind of mess with the PR history since I was still seeing the old commits although I thought I updated the code from your main. This is something I still do not understand from forks. I synched it on github but it still see the tco399  commits, see here:  

Schermata 2024-02-22 alle 10 38 47

I pushed directly to my main (not using any dev branch), I thought that I could use the fork exactly as a branch. Probably I should have done some `git merge upstream/main` before opening the PR and not trust on github commands. 

I am ok with removing the gitignore, I simply did that for practical usage but it could fit easily another PR.

**Comment by uwefladrich** [comment]
I pushed, but something went wrong? Please wail while I sort out ...

**Comment by uwefladrich** [comment]
Okay, I think we are back on track. @oloapinivad, can you double check that things look allright? Then I can merge.

**Comment by oloapinivad** [comment]
Great, I have no idea what happened. The changes seems correct, I would merge it!

**Pull request merged**
