### PR TITLE
Support for tco399

### PR DESCRIPTION
**Pull request by oloapinivad**
I am creating files to support also Tco399. I planning to check if this works in EC-Earth in the next days...

### CODE REVIEW

**Review by uwefladrich — APPROVED** [review]
Looks good from my side! I have made style changes such that the grid definition is formatted the same way as the other grids.

**Comment by uwefladrich** [comment]
I generally use [isort](https://pycqa.github.io/isort/) (applied first) and then [Black](https://github.com/psf/black). However, the grid definition files require an extra, manual, step because Black will put every ``_lats`` and every ``_nlons`` value on a single line. I change that to have 5 ``_lats`` values in each line and 10 ``_nlons`` (regardless of the resulting line length). Some care is needed to not get any extra whitespaces.

**Comment by uwefladrich** [comment]
Do you intent to add more grids in this MR? Which grids are you thinking of? 

Did you have the chance to make any testing with Tco399 yet?

**Comment by oloapinivad** [comment]
Sorry for the delay! Yes, I tested and the weights were generated - apparently they were fine -, although I could not run the model because of the MPI issue. 

To me this can be merged, I will then include more grids in next weeks and perhaps prepare a script for the right formatting

**Comment by uwefladrich** [comment]
Great, I'll merge this PR then.

Do not bother too much with the formatting, I can do that easily if needed.

**Pull request merged**
