### PR TITLE
Consistent names for ECMWF base grids

### PR DESCRIPTION
**Pull request by uwefladrich**
rdy2cpl handles grid point grids and the [ECMWF convention](https://confluence.ecmwf.int/display/OIFS/4.1+OpenIFS%3A+Gaussian+grids) is:

- FXXX - full (regular) Gaussian grid with XXX latitude lines between the pole and equator
- NXXX - original ECMWF reduced Gaussian grid with XXX latitude lines between the pole and equator
- OXXX - octahedral ECMWF reduced Gaussian grid with XXX latitude lines between the pole and equator

However, rdy2cpl uses grid names referring to the spectral truncation (Tlxxx, Tcoxxx), which is irrelevant in this context.

Furthermore, rdy2cpl implements a regular Gaussian grid with the name `N128`. According to the convention above, NXXX is a *reduced* Gaussian grid, hence the rdy2cpl name for this grid is wrong.

### CODE REVIEW

**Comment by oloapinivad** [comment]
Looks very good. Does it make sense to create aliases for Tco/Tl grid to keep a sort of backward compatibility?

**Comment by uwefladrich** [comment]
> Looks very good. Does it make sense to create aliases for Tco/Tl grid to keep a sort of backward compatibility?

Is it really needed? The only place where this is used is our ECE4 scripts and we have control over this. So I think we can update the scripts (in particular only one file, `ece_coupling_grids.yml`) at the same time and would not have any issues. For me it would not be worth the effort (and maintenance). Is that okay?

**Comment by oloapinivad** [comment]
The only "minor" risk I see is that someone currently using ECE4 updates its environment so that it ends with a version of rdy2cpl not compatible with his/her own "older" version of ECE4.

But it is true that this should be a small hiccup which can be easily fixed...

**Comment by uwefladrich** [comment]
True. We can leave this PR open and therefore in i branch and then simultaneously we merge [!56](https://git.smhi.se/ec-earth/ecearth4/-/merge_requests/56) and this PR. This way, we can at least say that one needs to update both the ECE4 code and the environment at the same time. We can even point the `environment.yml` file in !56 to this branch for the time being, so there would be no manual downloading of the branch.

In the longer run, we need to make proper versions for rdy2cpl to handle this situation better.

**Pull request merged**
